samplesite/api/urls.py
from django.urls import path

from .views import bbs, BbDetailView, comments

urlpatterns = [
    path('bbs/<int:pk>/comments/', comments),
    path('bbs/<int:pk>/', BbDetailView.as_view()),
    path('bbs/', bbs),
]

samplesite/main/urls.py
from django.urls import path
from .views import rubric_bbs, bb_detail, profile_bb_detail, profile_bb_add, profile_bb_edit, profile_bb_delete
from django.conf import settings
from django.conf.urls.static import static

from .views import (index, other_page, BBloginView, profile,
                    BBLogoutView, ProfileEditView, PasswordEditView, RegisterView,
                    RegisterDoneView, user_activate, ProfileDeleteView)

app_name = 'main'
urlpatterns = [
    path('accounts/profile/delete/', ProfileDeleteView.as_view(), name='profile_delete'),
    path('accounts/activate/<str:sign>/', user_activate, name='activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/password/edit/', PasswordEditView.as_view(), name='password_edit'),
    path('accounts/profile/edit/', ProfileEditView.as_view(), name='profile_edit'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/profile/edit/<int:pk>/', profile_bb_edit, name='profile_bb_edit'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/login/', BBloginView.as_view(), name='login'),
    path('<int:rubric_pk>/<int:pk>/', bb_detail, name='bb_detail'),
    path('<int:pk>/', rubric_bbs, name='rubric_bbs'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

samplesite/samplesite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/', include('api.urls')),
    path('', include('main.urls')),
    # path('bboard/', include('bboard.urls')),
]

samplesite/main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

from .models import AdvUser, SuperRubric, SubRubric, Bb, AdditionalImage, Comment
from .signals import post_register


class SubRubricForm(forms.ModelForm):
    super_rubric = forms.ModelChoiceField(queryset=SuperRubric.objects.all(), empty_label=None,
                                          label='Надрубрика', required=True)

    class Meta:
        model = SubRubric
        fields = '__all__'


class RegisterForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput,
                                help_text='Пожалуйста, введите тот же самый пароль еще раз')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError('Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        post_register.send(RegisterForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')


class ProfileEditForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')

class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label='Поиск')

class BbForm(forms.ModelForm):
    class Meta:
        model = Bb
        fields = '__all__'
        widgets = {'author'  : forms.HiddenInput}

AIFormSet = forms.inlineformset_factory(Bb, AdditionalImage, fields='__all__')

class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}

class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label = 'Введите текст с картинки', error_messages = {'invalid': 'Неправильный текст'})

    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'bb': forms.HiddenInput}

samplesite/main/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.core.signing import BadSignature
from django.core.paginator import Paginator
from django.contrib.auth import logout
from django.db.models import Q


from .models import AdvUser, SubRubric, Bb, Comment
from .forms import ProfileEditForm, RegisterForm, SearchForm, BbForm, AIFormSet, UserCommentForm, GuestCommentForm
from .utilities import signer

"""
    rubric_bbs - функция-обработчик, 
    отображает объявления, относящиеся к рубрике, 
    с возможностью поиска
"""


def rubric_bbs(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=rubric)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(bbs, 2)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'rubric': rubric, 'page': page,
               'bbs': page.object_list, 'form': form}
    return render(request, 'main/rubric_bbs.html', context)


"""
    ProfileDeleteView - класс-обработчик, 
    предназначен для удаления пользовательской учетной записи
"""


class ProfileDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'main/profile_delete.html'
    success_url = reverse_lazy('main:index')
    success_message = 'Пользователь удален'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


"""
    user_activate - функция-обработчик, 
    активирует пользовательскую учетную запись
"""


def user_activate(request, sign):
    try:
        user = signer.unsign(sign)
    except BadSignature:
        return render(request, 'main/activation_failed.html')
    user = get_object_or_404(AdvUser, username=user)
    if user.is_activated:
        template = 'main/activation_done_earlier.html'
    else:
        template = 'main/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)


"""
    RegisterDoneView - класс-обработчик, 
    отображает сообщение после регистрации
"""


class RegisterDoneView(TemplateView):
    template_name = 'main/register_done.html'


"""
    RegisterView - класс-обработчик, 
    регистрирует нового пользователя
"""


class RegisterView(CreateView):
    model = AdvUser
    template_name = 'main/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('main:register_done')


"""
    PasswordEditView - класс-обработчик, 
    меняет пароль зарегистрированного пользователя
"""


class PasswordEditView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_edit.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'


"""
    ProfileEditView - класс-обработчик, 
    изменяет профиль зарегистрированного пользователя
"""


class ProfileEditView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/profile_edit.html'
    form_class = ProfileEditForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


"""
    BBLogoutView - класс-обработчик, 
    выполняет выход из системы
"""


class BBLogoutView(LogoutView):
    pass


"""
    profile - функция-обработчик, 
    отображает профиль зарегистрированного пользователя
"""


@login_required
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {'bbs': bbs}
    return render(request, 'main/profile.html', context)


"""
    BBloginView - класс-обработчик, 
    выполняет вход в систему
"""


class BBloginView(LoginView):
    template_name = 'main/login.html'


"""
    index - функция-обработчик, 
    отображает главную страницу
"""


def index(request):
    bbs = Bb.objects.filter(is_active=True).select_related('rubric')[:10]
    context = {'bbs': bbs}
    return render(request, 'main/index.html', context)


"""
    other_page - функция-обработчик, 
    отображает страницы, не относящиеся к объявлениям
"""


def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def bb_detail(request, rubric_pk, pk):
    bb = Bb.objects.get(pk=pk)
    initial = {'bb': bb.pk}

    if request.user.is_authenticated:
        initial['author'] =request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == 'POST':
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, 'Комментарий добавлен')
            return redirect(request.get_full_path_info())
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, 'Комментарий не добавлен')
    
    ais = bb.additionalimage_set.all()
    comments = Comment.objects.filter(bb=pk, is_active=True)
    context = {'bb': bb, 'ais': ais, 'comments': comments, 'form': form}
    return render(request, 'main/bb_detail.html', context)

@login_required
def profile_bb_detail(request, pk):
    bb = get_object_or_404(Bb, pk=pk, author=request.user)
    ais = bb.additionalimage_set.all()
    context = {'bb': bb, 'ais': ais}
    return render(request, 'main/bb_detail.html', context)

@login_required
def profile_bb_add(request):
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, "Объявление добавлено")
                return redirect('main:profile')
    else:
        form = BbForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_add.html', context)

@login_required
def profile_bb_edit(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, "Объявление отредактировано")
                return redirect('main:profile')
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
    context = {'form': form, 'formset': formset}
    return render(request, 'main/profile_bb_edit.html', context)

@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == 'POST':
        bb.delete()
        messages.add_message(request, messages.SUCCESS, "Объявление удалено")
        return redirect('main:profile')
    else:
        context = {'bb' : bb}
        return render(request, 'main/profile_bb_delete.html', context)

samplesite/main/templates/main/activation_done.html
{% extends 'layout/basic.html' %}
{% block title %}Активация выполнена{% endblock %}
{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем успешно активирован.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

samplesite/main/templates/main/activation_done_earlier.html
{% extends 'layout/basic.html' %}
{% block title %}Пользователь уже активирован{% endblock %}
{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем был активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти на сайт</a></p>
{% endblock %}

samplesite/main/templates/main/activation_failed.html
{% extends 'layout/basic.html' %}
{% block title %}Ошибка при активации{% endblock %}
{% block content %}
<h2>Активация</h2>
<p>Активация пользователя с таким именем прошла неудачна.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироваться повторно</a></p>
{% endblock %}

samplesite/main/templates/main/bb_detail.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}{{ bb.title }} - {{ bb.rubric.name }}{% endblock %}

{% block content %}
<div class="row mt-3">
    {% if bb.image %}
    <div class="col-md-auto">
        <img src="{{ bb.image.url }}" class="main-image">
    </div>
    {% endif %}
    <div class="col">
        <h2>{{ bb.title }}</h2>
        <p>{{ bb.content }}</p>
        <p class="fw-bold">{{ bb.price}} руб.</p>
        <p>{{ bb.contacts }}</p>
        <p class="text-end fst-italic">Добавлено {{ bb.created_at}}</p>
    </div>
</div>
{% if ais %}
<div class="d-flex justify-content-between flex-wrap mt-5">
    {% for ai in ais %}
    <div class="d-flex justify-content-center align-items-center">
        <img class="additional-image" src="{{ ai.image.url }}">
    </div>
    {% endfor %}
</div>
{% endif %}
<h4 class="mt-5">Новый комментарий</h4>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Добавить' %}
</form>
{% if comments %}
<div class="vstack gap-3 mt-5">
    {% for comment in comments %}
    <div class="p-2 border">
        <h5>{{ comment.author }}</h5>
        <p>{{ comment.content }}</p>
        <p class="text-end fst-italic">{{ comment.created_at }}</p>
        </div>
    {% endfor %}
</div>
{% endif %}
<p><a href="{% url 'main:rubric_bbs' pk=bb.rubric.pk %}{{ all }}">Назад</a></p>
{% endblock %}

samplesite/main/templates/main/login.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Вход{% endblock %}

{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход.</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% bootstrap_button 'Войти' %}
</form>
{% endif %}
{% endblock %}

samplesite/main/templates/main/password_edit.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
<h2>Смена пароля пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Сохранить' %}
</form>
{% endblock %}

samplesite/main/templates/main/profile.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}


{% block title %}Профиль пользователя{% endblock %}

{% block content %}
<h2>Профиль пользователя {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<h3>Ваши объявления</h3>
<p><a href="{% url 'main:profile_bb_add' %}">Добавить объявление</a></p>

</form>
{% if bbs %}
<div class="vstack gap-3 my-4">
    {% for bb in bbs %}
    <div class="card">
        {% url 'main:bb_detail' rubric_pk=bb.rubric.pk pk=bb.pk as url %}
        <div class="row p-3">
            <a class="col-md-2" href="{{ url }}{{ all }}">
                {% if bb.image %}
                <img class="img-fluid" src="{% thumbnail bb.image 'default' %}">
                {% else %}
                <img class="img-fluid" src="{% static 'main/empty.jpg' %}">
                {% endif %}
            </a>
            <div class="col-md-10 card-body">
                <h3 class="card-title"><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                <div class="card-text mb-2">{{ bb.content }}</div>
                <p class="card-text text-end">
                    <a href="{% url 'main:profile_bb_edit' pk=bb.pk %}">Исправить</a>
                    <a href="{% url 'main:profile_bb_delete' pk=bb.pk %}">Удалить</a>
                </p>
                <p class="card-text fw-bold">{{ bb.price }} руб.</p>
                <p class="card-text text-end fst-italic">{{ bb.created_at }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

samplesite/main/templates/main/profile_bb_add.html
{% extends 'layout/basic.html' %}

{% load django_bootstrap5 %}

{% block title %}Добавление объявления - Профиль пользователя{% endblock %}

{% block content %}
<h2> Добавления объявления </h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_formset formset layout='horizontal' %}
    {% bootstrap_button 'Добавить' %}
</form>
{% endblock %}

samplesite/main/templates/main/profile_bb_edit.html
{% extends "layout/basic.html" %}
{% load django_bootstrap5 %}
{% block title %}Правка объявления{% endblock %}

{% block content %}
<h2>Правка объявления {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Сохранить' %}
</form>
{% endblock %}

samplesite/main/templates/main/profile_delete.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Удаление пользователя{% endblock %}
{% block content %}
<h2>Удаление пользователя {{ object.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_button 'Удалить' button_class='btn-danger' %}
</form>
{% endblock %}

samplesite/main/templates/main/profile_edit.html
{% extends "layout/basic.html" %}
{% load django_bootstrap5 %}
{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Сохранить' %}
</form>
{% endblock %}

samplesite/main/templates/main/register.html
{% extends 'layout/basic.html' %}
{% load django_bootstrap5 %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button 'Зарегистрироваться' %}
</form>
{% endblock %}

samplesite/main/templates/main/register_done.html
{% extends 'layout/basic.html' %}
{% block title %}Регистрация завершена{% endblock %}
{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>
{% endblock %}

samplesite/main/templates/main/rubric_bbs.html
{% extends 'layout/basic.html' %}

{% load thumbnail %}
{% load static %}
{% load django_bootstrap5 %}

{% block title %}{{ rubric }}{% endblock %}

{% block content %}

<h2 class="mb-2">{{ rubric }}</h2>
<form class="row row-cols-md-auto justify-content-end">
    {% bootstrap_field form.keyword show_label=False wrapper_class='col-12' %}
    <div class="col-12">
        {% bootstrap_button 'Искать' %}
    </div>
</form>
{% if bbs %}
<div class="vstack gap-3 my-4">
    {% for bb in bbs %}
    <div class="card">
        {% url 'main:bb_detail' rubric_pk=rubric.pk pk=bb.pk as url %}
        <div class="row p-3">
            <a class="col-md-2" href="{{ url }}{{ all }}">
                {% if bb.image %}
                <img class="img-fluid" src="{% thumbnail bb.image 'default' %}">
                {% else %}
                <img class="img-fluid" src="{% static 'main/empty.jpg' %}">
                {% endif %}
            </a>
            <div class="col-md-10 card-body">
                <h3 class="card-title"><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                <div class="card-text mb-2">{{ bb.content }}</div>
                <p class="card-text fw-bold">{{ bb.price }} руб.</p>
                <p class="card-text text-end fst-italic">{{ bb.created_at }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% bootstrap_pagination page url=keyword %}
{% endif %}
{% endblock %}